### ISSUE TITLE
Minor changes to package.json required

### ISSUE THREAD

**Issue by phuedx** [kodchi/mediawiki-services-chromium-render#1]
AFAICT there are two minor tweaks that we need to make to package.json prior to deploying the service:

* [ ] Update the required version of Node.js [on L57](https://github.com/kodchi/mediawiki-services-chromium-render/blob/master/package.json#L57) to 6.4.0 per [T176627#3662455](https://phabricator.wikimedia.org/T176627#3662455)
* [ ] Add chromium to [the list of deployment dependences](https://github.com/kodchi/mediawiki-services-chromium-render/blob/67d95fb6f4acc66973a0e0ecf649d296d07aa663/package.json#L60-L97)

**Comment by kodchi** [comment]
Why downgrade to 6.4 when we can use 6.9? I should have been clearer that puppeteer requires at least 6.4.

Chromium will be downloaded by puppeteer on the first launch.

**Comment by phuedx** [comment]
This request is now tracked by [T178186](https://phabricator.wikimedia.org/T178186).
